---
# tasks file for wordpress
 - name: Download Wp
   get_url:
     url: https://wordpress.org/latest.tar.gz
     dest: /tmp/wordpress.tar.gz
     validate_certs: no

 - name: Extract Wp
   unarchive:
     src: /tmp/wordpress.tar.gz
     dest: /var/www/html
     remote_src: True

 - name: Update the default Apache site
   lineinfile:
     path: /etc/apache2/sites-enabled/000-default.conf
     regexp: "(.)+DocumentRoot /var/www/html"
     line: "DocumentRoot /var/www/html/wordpress"
   notify:
     - restart apache

 - name: Copy wp-config-sample.php to wp-config.php
   command: cp /var/www/html/wordpress/wp-config-sample.php /var/www/html/wordpress/wp-config.php

 - name: update database credentials
   lineinfile:
     path: /var/www/html/wordpress/wp-config.php
     regexp: "{{ item.regexp }}"
     line: "{{ item.line }}"
   with_items:
      - {'regexp': "define\\('DB_NAME', '(.)+'\\);", 'line': "define('DB_NAME', '{{wp_mysql_db}}');"}
      - {'regexp': "define\\('DB_USER', '(.)+'\\);", 'line': "define('DB_USER', '{{wp_mysql_user}}');"}
      - {'regexp': "define\\('DB_PASSWORD', '(.)+'\\);", 'line': "define('DB_PASSWORD', '{{wp_mysql_pass}}');"}
