---
# tasks file for php
 - name: Install PHP and extensions
   apt:
     name: "{{ item }}"
     state: present

   with_items:
     - php5
     - libapache2-mod-php5
     - php5-mcrypt
     - php5-gd
     - libssh2-php
